/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDevisRouteImport } from './routes/api/devis'
import { Route as ApiGoogleReviewsRouteImport } from './routes/api/google-reviews'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevisRoute = ApiDevisRouteImport.update({
  id: '/api/devis',
  path: '/api/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleReviewsRoute = ApiGoogleReviewsRouteImport.update({
  id: '/api/google-reviews',
  path: '/api/google-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/realisations': typeof RealisationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/devis': typeof ApiDevisRoute
  '/api/google-reviews': typeof ApiGoogleReviewsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/realisations': typeof RealisationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/devis': typeof ApiDevisRoute
  '/api/google-reviews': typeof ApiGoogleReviewsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/realisations': typeof RealisationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/devis': typeof ApiDevisRoute
  '/api/google-reviews': typeof ApiGoogleReviewsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/realisations'
    | '/api/chat'
    | '/api/devis'
    | '/api/google-reviews'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/realisations'
    | '/api/chat'
    | '/api/devis'
    | '/api/google-reviews'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/realisations'
    | '/api/chat'
    | '/api/devis'
    | '/api/google-reviews'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RealisationsRoute: typeof RealisationsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDevisRoute: typeof ApiDevisRoute
  ApiGoogleReviewsRoute: typeof ApiGoogleReviewsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devis': {
      id: '/api/devis'
      path: '/api/devis'
      fullPath: '/api/devis'
      preLoaderRoute: typeof ApiDevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-reviews': {
      id: '/api/google-reviews'
      path: '/api/google-reviews'
      fullPath: '/api/google-reviews'
      preLoaderRoute: typeof ApiGoogleReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RealisationsRoute: RealisationsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDevisRoute: ApiDevisRoute,
  ApiGoogleReviewsRoute: ApiGoogleReviewsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
